FROM python:3.11-slim

RUN apt-get update && apt-get install -y --no-install-recommends     build-essential libopenblas-dev wget   && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .
ENV PORT=8080
ENV STREAMLIT_SERVER_HEADLESS=true
ENV STREAMLIT_BROWSER_GATHER_USAGE_STATS=false

COPY boot.sh /app/boot.sh
RUN chmod +x /app/boot.sh

CMD ["/bin/bash", "/app/boot.sh"]
