OPENAI_API_KEY = "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"
app_user = "admin123"
app_pass = "BestOrg123@#"
[gdrive]
type = "service_account"
project_id = "ai-ceo-knowledge-system"
private_key_id = "87cef8c14e2d954d95f0eef56d8e539938cb783c"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQChrYeBTuhw5Ko7
V56sTgdUonD3TVC/DPZcIlcI6LHhHR5l8XYy3ZcqenpWfcRvQNbuQ0Aem4CQQFCb
BwEAOoK2peAqwOGfY9TGx+pCbDN5CkHMtP32huDXI4sbk7JzvDepKPis3jcTUSRf
laJWUWeQAaTdK1ReLPkiSzJOz9KzU2i1G1ZsefgdA9JMtkPWEd0g0XHqxj4mE7zG
PO29y/hDvtT1Q6KdYxbIW2Hakxwi0LEHjtA1V6ccDq5c/ysSLk/td1viUC3JPbjs
egxyGj/VjMFwOgEniwTgpzW9enCUN2WrVTrNOktmr12BPvApc/nzelefr4kHO4NX
tOvrbSg5AgMBAAECggEADzFC5MgTwtqp6G5LrxNHUGZR89skYEoz3Y/YhTIggkUo
ixnNKpXJ/lLeAMH2syGbphipriFHS8bPYZH0lR8/vdwJHDCzGDWFqVw1y3dmwClS
P43ZDiZkewg6/89kMHNE+QoBkXTxe0jfqx+2I82odqQWPYuJylkIMXccIMMZ9dcV
YzgbQX26DQem8kreS+h/UTaXGJ6WHjl7FsHv9ZzCQGjKCxeTvpviJOhbZP49mcII
JwZ66JefeYqsOhALP3ek/dsZvWRnUjjs413HsNI6zXiGfS1LRZKHzjby+uY48EgV
xRBYgFylnL71t1WLk7czkHUxGn4rqxF2JFWM9QG5VQKBgQDSwb+YS8FlSM7Duh+d
1kaZJdgyH4NmUUBdkx2+LHBXKkpwk3+pZ2GLQc9xCRctKadUEEDYQBnrLHTEMkUF
JOhReppgjkHCBseM19ltfiNxQtv4luDlbBFNS/Prlk5MKIm7G1F9aBajLpNt8coC
kfnEwCSC2dD8ldG7Xeafcit+1wKBgQDEYp6xE+sScbMOPgsdtx/5puVWm2ZeTaTU
GPy8fnELGFu49BQyJ1jvTS/2Tgc5Aktifg+hcs0T1ctPIwaGxt4UDte7qiexgFsF
yGN4Muryjp3w+eRuZ/hdPyVyHyQcuR8pyY5dduIk9BdYCl4RhliUhSeRhro5Tr0b
FQThqG//bwKBgQCXmSAdB1jsZwu7hFUbrrcHkE5L95kH7ygSZzE8yzBfsp7rDV4F
18Q1bDgwAa73IIApGqvaIXnDTS4MtnApPBwUB9Gl5I3uZ/wAFn9ioBoUbVhXHwhU
XoCvjhO9gVd+tqYjvYnHYCjwZh9MNWDuqlv0J5XbvZvzJD1BvlCWnoQk7wKBgQDA
42Se5MN1ADwwdvwQGbfMTALiCAyJ/5UvxcMnmMGLdkdQ6FuVz1Po51V+hLFPa1OD
z/GmT83h95GTjwFwC5BA/zsh1kTacQn2KhaZDtn5l97Fu4yEbJZjcAxlhPTBSYq0
ToYIgyYnyZ/MF5LBf8UtS4PLyhrLAu121jRPOFOY/QKBgFQRq+OQajVTbC3an+Xi
GLSzC1QpCiaxz7d4Yt6MM+JMhGs14VlykjgoC/OEWuVfDH9tU/HpG3L50MrAXKE+
AsVtL90s8DIpJSFhFa695j5v/tu3y1uostBhio2r5cUcnFeRAvNV4H6ndNSCoB0q
UIJhtxhkrpZCsqYgPRRgdLgq
-----END PRIVATE KEY-----"""
client_email = "ai-ceo-knowledgebase-project@ai-ceo-knowledge-system.iam.gserviceaccount.com"
client_id = "116177369236689196468"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/ai-ceo-knowledgebase-project%40ai-ceo-knowledge-system.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
